# Generated by Django 4.0.1 on 2022-02-28 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_notes_created_on_alter_notes_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='discription',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
    ]
