# Generated by Django 4.0.1 on 2022-02-28 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_notes_discription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='discription',
            field=models.TextField(max_length=255, null=True, verbose_name='Описание'),
        ),
    ]
