# Generated by Django 4.0.1 on 2022-03-05 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_notes_discription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='image',
            field=models.ImageField(blank='documents/latest-news.png', null=True, upload_to='Изображение'),
        ),
    ]
