# Generated by Django 4.0.1 on 2022-03-06 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_rename_product_gallery_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='notes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Изображения', to='news.notes'),
        ),
    ]
